[changelog]
header = ""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first | trim }}
{% endfor %}
{% endfor %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_parsers = [
  { message = "^feat", group = "✨ 新機能" },
  { message = "^fix", group = "🐛 修正" },
  { message = "^docs", group = "📝 ドキュメント" },
  { message = "^style", group = "🎨 改善" },
  { message = "^refactor", group = "♻️ リファクタリング" },
  { message = "^perf", group = "⚡ パフォーマンス" },
  { message = "^test", group = "✅ テスト" },
  { message = "^chore|^ci", group = "🔧 その他" },
  { message = ".*", group = "📌 変更" },
]
filter_commits = false
tag_pattern = "v[0-9]*"
sort_commits = "oldest"
