[changelog]
header = ""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {{ commit.message | split(pat="\n") | first | trim }}
{% endfor %}
{% endfor %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_parsers = [
  { message = "^feat", group = "✨ 新機能" },
  { message = "^fix", group = "🐛 修正" },
  { message = "^perf", group = "⚡ パフォーマンス改善" },
  { message = "^docs", skip = true },
  { message = "^style", skip = true },
  { message = "^refactor", skip = true },
  { message = "^test", skip = true },
  { message = "^chore|^ci|^build", skip = true },
  { message = ".*", group = "📌 その他の変更" },
]
filter_commits = true
tag_pattern = "v[0-9]*"
sort_commits = "oldest"
